[package]
name = "cw-derive"
version = "0.13.2"
authors = ["Bart≈Çomiej Kuras <bart.k@confio.gmbh>"]
edition = "2018"
description = "Utilities for generating trait based contracts"
license = "Apache-2.0"
repository = "https://github.com/CosmWasm/cw-plus"
homepage = "https://cosmwasm.com"
documentation = "https://docs.cosmwasm.com"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1", features = ["parsing", "derive", "fold", "visit"] }
quote = "1"
proc-macro2 = "1"
convert_case = "0.4"
proc-macro-error = "1"

[dev-dependencies]
serde = { version = "1", features = ["derive"] }
cosmwasm-std = { version = "1.0.0-rc.0" }
cw-storage-plus = "0.13.2"
schemars = "0.8"
anyhow = "1"
