[package]
name = "cw-multi-test"
version = "0.10.0"
authors = ["Ethan Frey <ethanfrey@users.noreply.github.com>"]
edition = "2018"
description = "Test helpers for multi-contract interactions"
license = "Apache-2.0"
repository = "https://github.com/CosmWasm/cw-plus"
homepage = "https://cosmwasm.com"
documentation = "https://docs.cosmwasm.com"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["iterator", "staking"]
iterator = ["cosmwasm-std/iterator"]
stargate = ["cosmwasm-std/stargate"]
staking = ["cosmwasm-std/staking"]
backtrace = ["anyhow/backtrace"]

[dependencies]
cw0 = { path = "../../packages/cw0", version = "0.10.0" }
cw-storage-plus = { path = "../../packages/storage-plus", version = "0.10.0"}
cosmwasm-std = { version = "1.0.0-beta", features = ["staking"] }
cosmwasm-storage = { version = "1.0.0-beta" }
itertools = "0.10.1"
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
prost = "0.8.0"
anyhow = "1"
thiserror = "1"
derivative = "2"
