[package]
name = "cw-multi-test"
version = "0.3.2"
authors = ["Ethan Frey <ethanfrey@users.noreply.github.com>"]
edition = "2018"
description = "Test helpers for multi-contract interactions"
license = "Apache-2.0"
repository = "https://github.com/CosmWasm/cosmwasm-plus"
homepage = "https://cosmwasm.com"
documentation = "https://docs.cosmwasm.com"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-std = { version = "0.12.0-alpha2" }
schemars = "0.7"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
