[package]
name = "cw20-atomic-swap"
version = "0.4.0"
authors = ["Mauro Lacy <maurolacy@users.noreply.github.com>"]
edition = "2018"
description = "Implementation of Atomic Swaps"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all init/handle/query exports
library = []

[dependencies]
cw0 = { path = "../../packages/cw0", version = "0.4.0" }
cw2 = { path = "../../packages/cw2", version = "0.4.0" }
cw20 = { path = "../../packages/cw20", version = "0.4.0" }
cosmwasm-std = { git = "https://github.com/CosmWasm/cosmwasm.git", branch = "derive-entry-point", features = ["iterator"] }
cosmwasm-storage = { git = "https://github.com/CosmWasm/cosmwasm.git", branch = "derive-entry-point", features = ["iterator"] }
schemars = "0.7"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.20" }
hex = "0.3.1"
sha2 = "0.8.0"

[dev-dependencies]
cosmwasm-schema = { git = "https://github.com/CosmWasm/cosmwasm.git", branch = "derive-entry-point" }
