[package]
name = "cw1155"
version = "0.12.1"
authors = ["Huang Yi <huang@crypto.com>"]
edition = "2018"
description = "Definition and types for the CosmWasm-1155 interface"
license = "Apache-2.0"
repository = "https://github.com/CosmWasm/cw-plus"
homepage = "https://cosmwasm.com"
documentation = "https://docs.cosmwasm.com"

[dependencies]
cw-utils = { path = "../../packages/utils", version = "0.12.1" }
cosmwasm-std = { version = "1.0.0-beta5" }
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }

[dev-dependencies]
cosmwasm-schema = { version = "1.0.0-beta5" }
