[package]
name = "cw-storage-macro"
version = "0.13.4"
authors = ["yoisha <48324733+y-pakorn@users.noreply.github.com>"]
edition = "2018"
description = "Macro helpers for storage-plus"
license = "Apache-2.0"
repository = "https://github.com/CosmWasm/cw-plus"
homepage = "https://cosmwasm.com"
documentation = "https://docs.cosmwasm.com"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.96", features = ["full"] }

[dev-dependencies]
cw-storage-plus = { version = "0.13.4", path = "../storage-plus" }
cosmwasm-std = { version = "1.0.0", default-features = false }
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
