[package]
name = "cw-storage-plus"
version = "0.10.0"
authors = ["Ethan Frey <ethanfrey@users.noreply.github.com>"]
edition = "2018"
description = "Enhanced/experimental storage engines"
license = "Apache-2.0"
repository = "https://github.com/CosmWasm/cw-plus"
homepage = "https://cosmwasm.com"
documentation = "https://docs.cosmwasm.com"

[features]
default = ["iterator"]
iterator = ["cosmwasm-std/iterator"]

[dependencies]
cosmwasm-std = { version = "1.0.0-beta", default-features = false }
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
