[package]
name = "cw-storage-plus"
version = "0.3.2"
authors = ["Ethan Frey <ethanfrey@users.noreply.github.com>"]
edition = "2018"
description = "Enhanced/experimental storage engines"
license = "Apache-2.0"
repository = "https://github.com/CosmWasm/cosmwasm-plus"
homepage = "https://cosmwasm.com"
documentation = "https://docs.cosmwasm.com"

[features]
iterator = ["cosmwasm-std/iterator"]

[dependencies]
cosmwasm-std = { version = "0.11.1" }
schemars = "0.7"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
