[package]
name = "cw20-base"
version = "0.1.0"
authors = ["Ethan Frey <ethanfrey@users.noreply.github.com>"]
edition = "2018"
description = "Basic implementation of a CosmWasm-20 compliant token"
license = "AGPL-3.0"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
#default = ["cranelift", "entrypoint"]
default = ["entrypoint"]
# entrypoint means to expose init, handle, query extern "C" functions
# disable this (default-features = false) if importing code for use in another contract
entrypoint = []
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]
#backtraces = ["cosmwasm-std/backtraces", "cosmwasm-vm/backtraces"]
#cranelift = ["cosmwasm-vm/default-cranelift"]
#singlepass = ["cosmwasm-vm/default-singlepass"]

[dependencies]
cw20 = { path = "../../packages/cw20", version = "0.1.0" }
cosmwasm-std = { version = "0.10.0-alpha2" }
cosmwasm-storage = { version = "0.10.0-alpha2" }
schemars = "0.7"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
snafu = { version = "0.6.3" }

[dev-dependencies]
# we only need to enable this if we use integration tests
#cosmwasm-vm = { version = "0.10.0-alpha2", default-features = false }
cosmwasm-schema = { version = "0.10.0-alpha2" }
